name: Verilate
on: [push]
jobs:
  verilate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update repository
        run: apt update
      - name: Install Packages
        run: apt install -y build-essential cmake verilator
      - name: Build
        run: cmake -Bbuild
