name: Verilate
on: [push]
jobs:
  verilate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: apt-get build-essential cmake verilator
      - run: cmake -Bbuild
