name: Verilate
on: [push]
jobs:
  verilate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: apt update
      - run: apt install build-essential cmake verilator
      - run: cmake -Bbuild
